#pragma once

#include "game_entity.hpp"
#include "game_component.hpp"
#include "test_component.hpp"
#include "camera/camera_component.hpp"
#include "renderer/renderer_component.hpp"
#include "renderer/mesh_renderer_component.hpp"
#include "renderer/sphere_renderer_component.hpp"
#include "renderer/cube_renderer_component.hpp"
#include "renderer/plane_renderer_component.hpp"
#include "renderer/circle_renderer_component.hpp"
#include "renderer/cylinder_renderer_component.hpp"
#include "renderer/arc_renderer_component.hpp"
#include "light/light_component.hpp"
#include "light/directional_light_component.hpp"
#include "light/point_light_component.hpp"
#include "game_scene.hpp"